src/producer/main.go
src/producer/producer.go
src/producer/producer_test.go

Issue #1 Task 2
Run all package tests in `producer`. Also gradually building the `main.go` file which is what I plan on the server actually to be running. To run it, do `go run producer.go main.go <OPTIONAL PORT ARG>`. Hit `Ctrl+C` to escape out of it for now.

Issue #1 Task 2

---

client/main.go
client/src/client.go
client/src/client_test.go

Issue #9 Testing 1-3

---

producer/src/keys/keys.go
producer/src/keys/keys_test.go

Issue 26 task 1 producer

---

client/keys/keys.go
client/keys/keys_test.go

issue26 task 1 client

---

client/src/client/client.go
client/src/client/client_test.go
client/src/main/main.go

Added GetUserInput, associated test, and infinite loop in main. Fixes file structure.

Issue #25 Added GetUserInput

---

producer/src/main/main.go
producer/src/producer/producer.go
producer/src/producer/producer_test.go

New PR with handler

---

producer/src/block/block.go
producer/src/block/block_test.go

Serialize function for block header information. Needs the 2d slice Data

Serialize with tests. Block Header only

---

producer/src/block/block.go
producer/src/block/block_test.go

Changed the return type of HashSHA256 to a slice rather than an array.

changed hash function signature

---

scripts/run_all_tests.sh

Created Master Test Script

---

producer/src/block/block_test.go

It's a small change, but it looks better lol.

Very minor change

---

producer/src/block/block.go
producer/src/block/block_test.go

Issue to follow upon PR approval.

Tests and function stubs for block deserialize/hashblock

---

producer/src/blockchain/blockchain.go
producer/src/blockchain/blockchain_test.go

Tests and function stubs for blockchain file i/o

---

client/src/client/client.go
client/src/client/client_test.go
client/src/main/main.go

Tests and function stub had to be changed due to technical difficulties.

Issue #73) Added ProcessCmdLineArgs()

---

travis.yml

I added a travis file to the root. I'm exploring using travis for continuous integration.
[https://travis-ci.org/SIGBlockchain/project_aurum](https://travis-ci.org/SIGBlockchain/project_aurum)
[https://docs.travis-ci.com/user/tutorial/](https://docs.travis-ci.com/user/tutorial/)
[https://docs.travis-ci.com/user/languages/go/](https://docs.travis-ci.com/user/languages/go/)
[https://docs.travis-ci.com/user/for-beginners/](https://docs.travis-ci.com/user/for-beginners/)

Exploring Travis CI

---

producer/src/block/block.go
producer/src/block/block_test.go

Updated Serialize function (thanks, Vineet) and the tests for data and dataLen. Added HashBlock and Deserialize functions.

HashBlock, Deserialize, and Serialize fix 

---

client/src/client/client.go
client/src/client/client_test.go

Issue to be used:
**Expected Date of Completion:** 10-March-2019
**Workspace:**
- `producer/src/client/client.go`
- `producer/src/client/client_test.go`
**Objective:**
This function will handle sending a stream of bytes to the producer. It is the first issue in a series that begins to connect the producer and the client together.
**Testing:**
The max length of our messages will be 1024, so for messages longer than that a for loop will need to be implemented while sending a stream.
**Resources:**
- [Go net package](https://golang.org/pkg/net/)

Tests and stub for client send

---

producer/src/blockchain/blockchain.go
producer/src/blockchain/blockchain_test.go

Phase one passed issue 66

---

producer/src/blockchain/blockchain_test.go

@bashbashbash @ramirez915 @arosso3 This PR needs to be approved in order to fix the blockchain test.

SQL statements will now execute in tests

---

producer/src/blockchain/blockchain.go

add block fix

---

producer/src/blockchain/blockchain_test.go

More blockchain test fixes and an additional grand testing function for multiple blocks

Had to fix some things, added an additional large test for multi-block additions

---

client/src/main/main.go

Please test the `-d` flag to see that log messages appear in console, and `-l` should generate a file and directory in `project_aurum/client/logs/logs.txt`. `-ltestfile.txt` should create a file and directory `project_aurum/client/logs/testfile.txt`.

Issue #83) Added Debug Mode

---

producer/src/blockchain/blockchain.go
producer/src/blockchain/blockchain_test.go

both functions pass their corresponding tests

getBlockByHeight and getBlockByPosition functions

---

producer/src/contract/contract.go
producer/src/contract/contract_test.go

**Expected Date of Completion:** 17-March-2019
**Workspace:**
- `producer/src/contract/contract.go`
- `producer/src/contract/contract_test.go`
**Objective:**
Review the way contracts work by reading through the [slides on them](https://github.com/SIGBlockchain/project_aurum/blob/dev/docs/Contracts.pdf).
Claims consume or "claim" unclaimed yields. Our yields live inside the UYP (unclaimed yield pool). When a claim is made, it removes a valid yield from that pool and stores some metadata about the yield. 
A Claim must have:
- The contract hash of the contract that the yield being claimed is stored in
- The index of the block that contract is stored in
- The index of the yield being claimed in the array of yields of that contract
- The claimant's public key
- The signature of the claimant …

Claim functions

---

client/src/client/client.go
client/src/client/client_test.go

Added ln.Close() to tests in order to be able to run multiple tests. Changed import path of producer since it will not actually work with relative import paths, here are a few resources on why relative import paths actually don't work in go, and why we should really start considering conforming to go package standards and structure the project to be contained in an consistent location, probably `go/src/github.com/SIGBlockchain/project_aurum`.
https://scene-si.org/2018/01/25/go-tips-and-tricks-almost-everything-about-imports/
https://stackoverflow.com/questions/38517593/relative-imports-in-go

Issue #79) Added SendToProducer()

---

producer/src/contract/contract.go

Fixed yeild struct

---

producer/src/contract/contract.go
producer/src/contract/contract_test.go

I commented out tests not related to yields to allow for the yields test to be executed.

Implemented yields

---

client/src/client/client.go
client/src/keys/keys.go
producer/src/block/block.go
producer/src/blockchain/blockchain.go
producer/src/keys/keys.go
producer/src/producer/producer.go

Updated most source files with godoc documentation notation

---

client/src/client/client.go
client/src/client/client_test.go
client/src/keys/keys.go
client/src/keys/keys_test.go

Wallet functions and encode/decode private key

---

producer/src/accounts/accounts.go
producer/src/accounts/accounts_test.go

MakeContract support for minting (aka inflation) contracts

---

producer/src/accounts/accounts.go
producer/src/accounts/accounts_test.go

Serialize contract to support null-sender contracts

---

producer/src/accounts/accounts.go
producer/src/accounts/accounts_test.go

Deserialize contract support for null sender

---

producer/src/accounts/accounts.go
producer/src/accounts/accounts_test.go

Insert new account into table

---

internal/producer/src/accounts/accounts.go
internal/producer/src/accounts/accounts_test.go

Issue #165 
Reused some code from `UpdateAccountBalanceTable`

Remaining Update table functions

---

internal/producer/src/accounts/accounts.go
internal/producer/src/accounts/accounts_test.go

Validate Contract incremental development

---

internal/producer/src/accounts/accounts.go
internal/producer/src/accounts/accounts_test.go
internal/producer/src/producer/producer.go
internal/producer/src/producer/producer_test.go

Genesis Block

---

internal/producer/src/producer/producer.go
internal/producer/src/producer/producer_test.go

Finished the two assigned functions and passed their tests

ReadGenesisHashes and GenerateGenesisHashFile functions completed

---

internal/producer/src/accounts/accounts.go
internal/producer/src/accounts/accounts_test.go

Get Account info feature

---

cmd/producer/main/main.go
cmd/producer/main/main_test.go
internal/producer/src/block/block.go
internal/producer/src/block/block_test.go

Added functionality to be able to producer blocks in a loop.

Production loop

---

internal/client/src/client/client.go
internal/client/src/client/client_test.go

Client Wallet Functions

---

cmd/client/main/main.go
cmd/client/main/main_test.go
internal/client/src/client/client.go
internal/client/src/client/client_test.go

Setup Wallet additional case

---

internal/producer/src/block/block.go
internal/producer/src/block/block_test.go

Issue #202
Function stub `Equals` is included.

Tests for Block comparison function

---

internal/producer/src/accounts/accounts.go
internal/producer/src/accounts/accounts_test.go
internal/producer/src/producer/producer_test.go

Splitting the ValidateContract function

---

internal/producer/src/accounts/accounts.go
internal/producer/src/accounts/accounts_test.go

Tests for Contract Comparison Function #203

---

internal/producer/src/block/block.go
internal/producer/src/block/block_test.go

`ToString` function for `Block` struct

---

internal/producer/src/accounts/accounts.go
internal/producer/src/accounts/accounts_test.go
internal/producer/src/producer/producer_test.go

Change return value for `ValidateContract`

---

internal/producer/src/accounts/accounts.go
internal/producer/src/accounts/accounts_test.go

`ToString` function for `Contract` struct #212

---

cmd/client/main/main_test.go
internal/client/src/client/client.go
internal/client/src/client/client_test.go
internal/handlers/handlers_test.go
internal/producer/src/accounts/accounts.go
internal/producer/src/accounts/accounts_test.go
internal/producer/src/block/block.go
internal/producer/src/block/block_test.go
internal/producer/src/blockchain/blockchain_test.go
internal/producer/src/hashing/hashing.go
internal/producer/src/hashing/hashing_test.go
internal/producer/src/producer/producer.go
internal/producer/src/producer/producer_test.go

Fracture block package

---

internal/producer/src/hashing/hashing.go
internal/producer/src/hashing/hashing_test.go

Equals - hash comparison

---

internal/producer/src/validation/validation.go
internal/producer/src/validation/validation_test.go

Pending validation function

---

internal/pendingpool/pendingpool.go
internal/pendingpool/pendingpool_test.go

Pending pool package

---

internal/handlers/handlers.go
internal/handlers/handlers_test.go

Statuses did not match when correct response was received

Changed account info handler status to statusok

---

cmd/handlers/main.go
internal/constants/constants.go
internal/endpoints/endpoints.go
internal/handlers/handlers.go
internal/handlers/handlers_test.go

Added locks to handler main, handler func and handler test.

---

cmd/handlers/main.go
internal/constants/constants.go
internal/endpoints/endpoints.go
internal/handlers/handlers.go
internal/handlers/handlers_test.go

Youngest block reassignment

---

internal/nettools/nettools.go

Added GetIP function that gets local IP

---

internal/endpoints/endpoints.go
internal/nettools/nettools.go
internal/requests/requests.go
internal/requests/requests_test.go

Get request blockpub add peer

---

internal/pendingpool/pendingpool.go
internal/producer/src/accountstable/accountstable.go
internal/producer/src/accountstable/accountstable_test.go
internal/producer/src/producer/producer.go
internal/producer/src/producer/producer_test.go
internal/producer/src/validation/validation.go
internal/producer/src/validation/validation_test.go

Change accounts package I/O function file parameter

---

cmd/main.go
internal/accountstable/accountstable.go
internal/accountstable/accountstable_test.go
internal/blockchain/blockchain_test.go
internal/producer/producer.go

Make ExchangeBetweenAccountsUpdateAccountBalanceTable function take in a contract as a parameter

---

internal/accountstable/accountstable.go

TestRecoverBlockchainMetadata from blockchain_test failing

---

internal/block/block.go
internal/block/block_test.go
internal/contracts/contracts.go
internal/contracts/contracts_test.go
internal/handlers/handlers_test.go
internal/requests/requests_test.go

Block & Contract Equals functions with receivers

---

cmd/main.go

Handler's version of main.go is in cmd

cmd main.go

---

internal/contracts/contracts.go
internal/contracts/contracts_test.go
internal/handlers/handlers.go
internal/requests/requests.go
internal/requests/requests_test.go

Contract to JSONcontract and vice versa

---

internal/jsonify/jsonify.go

Created Jsonify package with interface build function

#247 Jsonify

---

internal/docker/docker.go
internal/docker/docker_test.go

Setting up aurum docker package

---

internal/whatever/whatever.go
internal/whatever/whatever_test.go

This is my first PR! I'm so excited!

first commit

---

internal/taco/taco.go
internal/taco/taco_test.go

this is me practicing git. pls ignore

first commmit

---

internal/handlers/handlers_test.go

Go routine in TestContractRequestHandler

---

internal/endpoints/endpoints.go

added constant that shows the endpoint for incoming blocks

---

internal/handlers/handlers.go
internal/handlers/handlers_test.go

Now, when a 404 status not found is returned, there is a message in the response body.

updated error message

---

internal/block/block.go
internal/block/block_test.go

Allows a Block to be converted to a JSONBlock which can be marshalled easily.

Block json marhsalling

---

internal/requests/requests.go
internal/requests/requests_test.go

Preliminary submission for #360

Getblockbyhashrequest

---

internal/constants/constants.go
internal/sqlstatements/sqlstatements.go
internal/wallet/wallet.go

Wallet Address and Timestamp Table

---

internal/integration_testing/integration_testing.go
internal/integration_testing/integration_testing_test.go

Integration Testing package #351

---

internal/mock/mock.go
internal/mock/mock_test.go

Added Mock io Reader, test, and documentation

---

internal/jsonify/jsonify.go
internal/jsonify/jsonify_test.go

completed issue379

---

internal/sqlstatements/sqlstatements.go
internal/validation/validation.go
internal/validation/validation_test.go

Validate producer timestamp

---

.travis.yml
Dockerfile
cmd/config.json
docker-compose.ci.yml
internal/integration_testing/integration_testing_test.go
internal/requests/requests.go
scripts/down.ci.sh
scripts/up.ci.sh

Docker integration test for Contract Info Request

---

internal/publickey/publickey.go
internal/publickey/publickey_test.go

Created a New function, corresponding to issue: https://github.com/SIGBlockchain/project_aurum/issues/377
Also added unit tests (that pass)

Created New function for AurumPublicKey

---

internal/requests/requests.go
internal/requests/requests_test.go

Send Block Request

---

cmd/main.go

Main.go will now launch a gorotuine that will send requests to http://blockchain.acmapp.tech/peers to add the producer to the list of peers.
Proof ^

Posting to peer discovery list

---

cmd/settings/main.go

completed issue 379

---

internal/block/block.go
internal/block/block_test.go

Working on getting tests to pass - I believe the function has an error in converting string data to bytes

finished function and test, but test not passing

---

internal/ifaces/ifaces.go

created iface IBlockchainStreamer

---

internal/publickey/publickey.go

Create NewFromPublic and modify New to use it

---

bin/config.json
cmd/settings/main.go
internal/config/config.go
internal/config/config_test.go

Add way for producer to have a wallet address

---

internal/block/block.go
internal/block/block_test.go
internal/handlers/handlers.go
internal/handlers/handlers_test.go
internal/requests/requests.go
internal/requests/requests_test.go

Fix block.Marshal

---

internal/blockchain/blockchain.go
internal/ifaces/ifaces.go

Created an `ILedgerManager` interface and `LedgerManager` struct.
Related to issue: https://github.com/SIGBlockchain/project_aurum/issues/412

Create ILedgeManager 

---

internal/sqlstatements/sqlstatements.go

Completed issue #421

---

internal/accountstable/accountstable.go
internal/ifaces/ifaces.go

Please provide help coming up with better comments for receiver functions

completed issue410

---

internal/handlers/handlers.go
internal/handlers/handlers_test.go

Getblockfrombody AAA test and function

---

internal/privatekey/privatekey.go
internal/privatekey/privatekey_test.go

Issue #375
Added a new function for private key pkg.

New function for private key package

---

internal/privatekey/privatekey.go

Issue #398
Handled x509.MarshalECPrivateKey() error.

Unhandled error in GenerateNRandomKeys

---

internal/block/block.go
internal/constants/constants.go

BlockHeaderLength Constant

---

Dockerfile

The following changes should fix the merge conflicts that occur for the pr between dev and master,

Fix merge conflicts in dev branch
